---
title: "Welcome to the Alliance"
author:
  - name: Dean McCarthy
    url: https://oaiphblog.com
    affiliation: The Ohio Alliance for Innovation in Population Health
    affiliation_url: https://ohio.edu
date: 04-22-2021
output:
  distill::distill_article:
    self_contained: false
preview: https://www.ohio.edu/sites/ohio.edu.news/files/2020-02/rsz_20030725-cutler_hall.jpg
---

## An Interconnected System

I reflected on the interconnected nature of health as I considered my own journey. I think the growing connections also represented my own awareness and awakening about systems. The connections were always there, I just went on a journey to realize them.
I started out as a voice performance major in college. I was a single person on a stage focused on my communication with a group through my artistic activity. In sharing my interest, I gave voice lessons. I enjoyed the interaction and in helping someone else to express themselves in the way I did. One of my students had vocal nodules. I learned about how a speech-language pathologist had assisted my voice student in her voice use on a daily basis. I also learned about intersections in care related to the voice. Speech-language pathology was a field I really didn't know much about so I took time to educate myself on it. 

In addition to overlap in voice, I found there were overlaps with many of my interests. I took classes in speech-language pathology. I discovered that people who stutter don't stutter when they sing. Another intersection. What could people learn from each other? I worked in a summer program for adults who stutter. Stuttering was described as an ice-berg. The speech behaviors were only the tip of what people saw with a life time of emotional reactions and experiences lying underneath. Communication is contextual. Challenges in communication affect multiple people in multiple ways. One person’s challenge has an effect on the behavior of others in communicating. The cycle is interactive and iterative.

I learned there are people who cannot use their voice at all. People who have developmental disabilities such as cerebral palsy, autism spectrum disorder, Down syndrome, and intellectual disabilities may have speech impairments so significant that they cannot meet their daily communication needs. Likewise individuals who have had a stroke or traumatic brain injury may have language or speech problems that are significantly limiting. People may be temporarily unable to speak because about intubation or facial surgery, and people may experience progressive loss of speech due to conditions like ALS or Parkinson's Disease. Individuals with significant communication disabilities can benefit from augmentative and alternative communication (AAC) such as gestures, signs, picture communication symbols or boards, alphabet boards, or computer or tablet-based devices that can produce speech output. The range of people who could benefit was vast. The work involved a careful understanding of the needs and skills of each individual but also the needs and skills of family and caregivers along with the barriers and support in their communities and society in general. The work was magnified.

I thought I was part of a complex system and I knew my work was interdisciplinary. I worked with physical and occupational therapists, behavioral specialists, nurses, doctors, psychologists, psychiatrists, rehabilitation engineers, registered dietitians, social workers, teachers, and many of hath care professionals. I became part of interprofessional education efforts at Ohio University to find ways to improve coordination of services and to create a climate of mutual and ethical respect. I still didn't have the whole picture. The health of the people I worked with was socially determined. 

In 2016, the [Interprofessional Education Collaborative (IPEC)](https://www.ipecollaborative.org/) updated their standards to include a focus on population health. To truly make a difference I had to recognize the systems I was a part of. I had to see that things like access to care and food insecurity were problems that affected everything in a whole delivery system and had an interactive effect on me as a citizen in my community. It's not that these things weren't always there or that the work wasn't always being done. I needed to integrate it.
 
I needed an understanding of: 

+ The goals, perspectives, needs, and wants of the client I was working with 
+ The goals, perspectives, needs, and wants of the family/caregivers 
+ How family/caregiver goals may differ 
+ My role within a team of professionals 
+ The family's relationship with the team of professionals 
+ The service delivery structure 
+ The perspectives of other health professionals and seeing how we all are working to improve health 
+ How systems actually affect someone's health in positive and negative ways 
+ How health includes things like housing and transportation 
+ That the power to affect change relies on a team that spans the entire state, country and world. 
 
I support the Alliance in their mission because it is fundamental to improving health outcomes for Ohio. They understand and help to build the critical networks required.
 
 
**Office of the Dean**  
**John McCarthy, Ph.D., Interim Dean**

Grover Center W381, Ohio University, Athens OH 45701-2979  
Pronouns: He/Him/His  
T:740.593.4717 • mccarthj@ohio.edu  
twitter.com/sayitanywayou • twitter.com/CHSPOhio  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```



